name: Build and Test

on:
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake clang-tidy
        sudo apt-get install -y python3-pip rustc nodejs npm
        pip install -r python/requirements.txt

    - name: Build all the things
      run: ./scripts/build_all.sh

    - name: Test Python
      run: pytest python

    - name: Test Rust
      run: cargo test --release

    - name: Test Node
      run: cd node && npm install && npm test

    - name: Test C++
      run: cd build && ctest -V

    - name: Run benchmarks
      run: |
        pip install -r scripts/requirements.txt
        python scripts/run_benchmarks.py --csv-file results --num-runs 3 --num-objects 100000

    - name: Publish results
      uses: actions/upload-artifact@v2
      with:
        name: benchmarks
        path: results/benchmarks.png
