name: Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake clang-tidy
        sudo apt-get install -y python3 python3-pip
        pip3 install conan

    - name: Conan install
      run: |
        conan profile detect
        conan install . --output-folder=build --build=missing

    - name: Build and Test C++
      run: |
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        cmake --build .
        cmake --install .
        ctest -V

    - name: Build & Test Python Package
      run: |
        pip install .
        pip install -r python/tests/requirements.txt
        pytest
